services:
  # Config Server Replica Set (3 nodes)
  configsvr1:
    image: mongo:7
    container_name: configsvr1
    command: mongod --configsvr --replSet configrs --port 27017 --bind_ip_all
    volumes:
      - configsvr1_data:/data/db
    networks:
      - mongo_net

  configsvr2:
    image: mongo:7
    container_name: configsvr2
    command: mongod --configsvr --replSet configrs --port 27017 --bind_ip_all
    volumes:
      - configsvr2_data:/data/db
    networks:
      - mongo_net

  configsvr3:
    image: mongo:7
    container_name: configsvr3
    command: mongod --configsvr --replSet configrs --port 27017 --bind_ip_all
    volumes:
      - configsvr3_data:/data/db
    networks:
      - mongo_net

  # Shard 1
  shard1:
    image: mongo:7
    container_name: shard1
    command: mongod --shardsvr --replSet shard1rs --port 27017 --bind_ip_all
    volumes:
      - shard1_data:/data/db
    networks:
      - mongo_net

  # Shard 2
  shard2:
    image: mongo:7
    container_name: shard2
    command: mongod --shardsvr --replSet shard2rs --port 27017 --bind_ip_all
    volumes:
      - shard2_data:/data/db
    networks:
      - mongo_net

  # Mongos Router
  mongos:
    image: mongo:7
    container_name: mongos
    command: >
      mongos
      --configdb configrs/configsvr1:27017,configsvr2:27017,configsvr3:27017
      --bind_ip_all
      --port 27017
    ports:
      - "27017:27017"
    depends_on:
      - configsvr1
      - configsvr2
      - configsvr3
      - shard1
      - shard2
    networks:
      - mongo_net

  # Python worker (insertion + filtering + analysis)
  worker:
    image: ghcr.io/astral-sh/uv:python3.13-bookworm-slim
    container_name: worker
    volumes:
      - ./scripts:/scripts
      - ./outputs:/outputs
      - ./data_arch:/data_arch
      - ./pyproject.toml:/pyproject.toml
      - ./uv.lock:/uv.lock
    working_dir: /scripts
    command: tail -f /dev/null  # keeps container alive
    depends_on:
      - mongos
    networks:
      - mongo_net

networks:
  mongo_net:
    driver: bridge

volumes:
  configsvr1_data:
  configsvr2_data:
  configsvr3_data:
  shard1_data:
  shard2_data:
